In [2]:
import numpy as np
import pandas as pd
import scipy.stats as st

In [3]:
df = pd.read_csv('covid_19_indonesia_time_series_all.csv')
df

,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,Total Cases,Total Deaths,Total Recovered,...,Latitude,New Cases per Million,Total Cases per Million,New Deaths per Million,Total Deaths per Million,Total Deaths per 100rb,Case Fatality Rate,Case Recovered Rate,Growth Factor of New Cases,Growth Factor of New Deaths
0,3/1/2020,ID-JK,DKI Jakarta,2,0,0,2,39,20,75,...,-6.204699,0.18,3.60,0.0,1.84,0.18,51.28%,192.31%,NaN,NaN
1,3/2/2020,ID-JK,DKI Jakarta,2,0,0,2,41,20,75,...,-6.204699,0.18,3.78,0.0,1.84,0.18,48.78%,182.93%,1.00,1.00
2,3/2/2020,IDN,Indonesia,2,0,0,2,2,0,0,...,-0.789275,0.01,0.01,0.0,0.00,0.00,0.00%,0.00%,NaN,NaN
3,3/2/2020,ID-RI,Riau,1,0,0,1,1,0,1,...,0.511648,0.16,0.16,0.0,0.00,0.00,0.00%,100.00%,NaN,NaN
4,3/3/2020,ID-JK,DKI Jakarta,2,0,0,2,43,20,75,...,-6.204699,0.18,3.96,0.0,1.84,0.18,46.51%,174.42%,1.00,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31817,9/15/2022,ID-SA,Sulawesi Utara,37,0,0,37,52770,1213,50997,...,1.259638,14.01,19974.38,0.0,459.14,45.91,2.30%,96.64%,2.85,1.00
31818,9/15/2022,ID-SB,Sumatera Barat,13,0,3,10,104640,2371,102066,...,-0.850253,2.36,18959.11,0.0,429.59,42.96,2.27%,97.54%,6.50,1.00
31819,9/15/2022,ID-SS,Sumatera Selatan,16,0,1,15,82198,3376,78510,...,-3.216212,1.95,10002.74,0.0,410.83,41.08,4.11%,95.51%,3.20,1.00
31820,9/15/2022,ID-SU,Sumatera Utara,50,0,5,45,158866,3288,154924,...,2.191894,3.36,10680.15,0.0,221.04,22.10,2.07%,97.52%,1.92,1.00
31821,9/16/2022,IDN,Indonesia,2358,27,2997,-666,6405044,157876,6218708,...,-0.789275,8.89,24153.07,0.1,595.34,59.53,2.46%,97.09%,0.89,1.29

# Hipotesa
##### H0 : x_bar presentasi kematian setiap bulan pada tahun 2021 di indonesia <= 50%
##### H1 : x_bar presentasi kematian setiap bulan pada tahun 2021 di indonesia > 50%

In [4]:
df['Case Fatality Rate'] = pd.to_numeric(df['Case Fatality Rate'].str.rstrip('%'))
df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df = df[['Date', 'Year', 'Month', 'Location ISO Code', 'Location', 'New Cases', 'New Deaths',
       'New Recovered', 'New Active Cases', 'Total Cases', 'Total Deaths',
       'Total Recovered', 'Total Active Cases', 'Location Level',
       'City or Regency', 'Province', 'Country', 'Continent', 'Island',
       'Time Zone', 'Special Status', 'Total Regencies', 'Total Cities',
       'Total Districts', 'Total Urban Villages', 'Total Rural Villages',
       'Area (km2)', 'Population', 'Population Density', 'Longitude',
       'Latitude', 'New Cases per Million', 'Total Cases per Million',
       'New Deaths per Million', 'Total Deaths per Million',
       'Total Deaths per 100rb', 'Case Fatality Rate', 'Case Recovered Rate',
       'Growth Factor of New Cases', 'Growth Factor of New Deaths']]

In [7]:
case_fatality_rate = df[['Year', 'Month', 'Case Fatality Rate']].groupby(['Year', 'Month']).mean()
case_fatality_rate

            Case Fatality Rate
Year Month
2020 3               58.328317
     4               13.192294
     5                5.504793
     6                4.241057
     7                3.815041
     8                3.372986
     9                3.229143
     10               2.994433
     11               2.979962
     12               2.830074
2021 1                2.718553
     2                2.668918
     3                2.668673
     4                2.657514
     5                2.689806
     6                2.716190
     7                2.625023
     8                2.878332
     9                3.138838
     10               3.190590
     11               3.198467
     12               3.200525
2022 1                3.198544
     2                2.966398
     3                2.613336
     4                2.608571
     5                2.614415
     6                2.615600
     7                2.608636
     8                2.592525
     9                2.582347

In [8]:
CL = 95 # Confidence Level = 95%
t_stat, p_val = st.ttest_1samp(case_fatality_rate, 50)
print('P Value:', p_val)
print('T Statistics:', t_stat)
print(f'Alfa: {(100-CL)/100}')

P Value: [1.45804964e-21]
T Statistics: [-24.83727955]
Alfa: 0.05

## Kesimpulan
1. P Value > Alfa = x_bar is not Significant Different (Fail to Reject H0)
2. P Value < Alfa = x_bar is Significant different (Reject H0)
- cause P Value > Alfa :
        Fail to Reject H0